version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    depends_on:
      - backend
    networks:
      - mern-networks
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8001:8001"
    volumes:
      - .:/code
    depends_on:
      - mongodb
    networks:
      - mern-networks
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - mern-networks
networks:
  mern-networks:
    driver: bridge
volumes:
  mongodb:
  
